### ISSUE TITLE
`readline.__doc__` returns None

### ISSUE THREAD

**Issue by ahamaline** [pyreadline3/pyreadline3#19]
In Readline, `readline.__doc__`  returns either "Importing this module enables command line editing using GNU readline." or "Importing this module enables command line editing using libedit readline.". In many packages this is used to check what implementation is being used, for example using the condition
``if 'libedit' in readline.__doc__:``.
However, in pyreadline3, `readline.__doc__` returns None, meaning that any such check will throw an error.

**Comment by brgirgis** [comment]
fixed in 3.5.0
